name: Run grumphp with different versions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        phpstan: ['1', '2']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: COMPOSER_ROOT_VERSION=dev-main composer require phpstan/phpstan:^${{ matrix.phpstan }}
      - run: ./vendor/bin/grumphp run
